'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Namespace My
    
    <Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "10.0.0.0"),  _
     Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
    Partial Friend NotInheritable Class MySettings
        Inherits Global.System.Configuration.ApplicationSettingsBase
        
        Private Shared defaultInstance As MySettings = CType(Global.System.Configuration.ApplicationSettingsBase.Synchronized(New MySettings()),MySettings)
        
#Region "My.Settings Auto-Save Functionality"
#If _MyType = "WindowsForms" Then
    Private Shared addedHandler As Boolean

    Private Shared addedHandlerLockObject As New Object

    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
    Private Shared Sub AutoSaveSettings(ByVal sender As Global.System.Object, ByVal e As Global.System.EventArgs)
        If My.Application.SaveMySettingsOnExit Then
            My.Settings.Save()
        End If
    End Sub
#End If
#End Region
        
        Public Shared ReadOnly Property [Default]() As MySettings
            Get
                
#If _MyType = "WindowsForms" Then
               If Not addedHandler Then
                    SyncLock addedHandlerLockObject
                        If Not addedHandler Then
                            AddHandler My.Application.Shutdown, AddressOf AutoSaveSettings
                            addedHandler = True
                        End If
                    End SyncLock
                End If
#End If
                Return defaultInstance
            End Get
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Verdana, 10pt")>  _
        Public Property setDefaultFont() As Global.System.Drawing.Font
            Get
                Return CType(Me("setDefaultFont"),Global.System.Drawing.Font)
            End Get
            Set
                Me("setDefaultFont") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("True")>  _
        Public Property setRepeatPurposes() As Boolean
            Get
                Return CType(Me("setRepeatPurposes"),Boolean)
            End Get
            Set
                Me("setRepeatPurposes") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("True")>  _
        Public Property setRepeatOutputs() As Boolean
            Get
                Return CType(Me("setRepeatOutputs"),Boolean)
            End Get
            Set
                Me("setRepeatOutputs") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("True")>  _
        Public Property setShowIndicatorColumn() As Boolean
            Get
                Return CType(Me("setShowIndicatorColumn"),Boolean)
            End Get
            Set
                Me("setShowIndicatorColumn") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("True")>  _
        Public Property setShowVerificationSourceColumn() As Boolean
            Get
                Return CType(Me("setShowVerificationSourceColumn"),Boolean)
            End Get
            Set
                Me("setShowVerificationSourceColumn") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("True")>  _
        Public Property setShowAssumptionColumn() As Boolean
            Get
                Return CType(Me("setShowAssumptionColumn"),Boolean)
            End Get
            Set
                Me("setShowAssumptionColumn") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("True")>  _
        Public Property setShowResourcesBudget() As Boolean
            Get
                Return CType(Me("setShowResourcesBudget"),Boolean)
            End Get
            Set
                Me("setShowResourcesBudget") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Arial, 12pt, style=Bold")>  _
        Public Property setSysFont() As Global.System.Drawing.Font
            Get
                Return CType(Me("setSysFont"),Global.System.Drawing.Font)
            End Get
            Set
                Me("setSysFont") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Goals")>  _
        Public Property setStruct1() As String
            Get
                Return CType(Me("setStruct1"),String)
            End Get
            Set
                Me("setStruct1") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Purposes")>  _
        Public Property setStruct2() As String
            Get
                Return CType(Me("setStruct2"),String)
            End Get
            Set
                Me("setStruct2") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Outputs")>  _
        Public Property setStruct3() As String
            Get
                Return CType(Me("setStruct3"),String)
            End Get
            Set
                Me("setStruct3") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Activities")>  _
        Public Property setStruct4() As String
            Get
                Return CType(Me("setStruct4"),String)
            End Get
            Set
                Me("setStruct4") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property setLogframeHideEmptyCells() As Boolean
            Get
                Return CType(Me("setLogframeHideEmptyCells"),Boolean)
            End Get
            Set
                Me("setLogframeHideEmptyCells") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("True")>  _
        Public Property setLayOutToolBarVisible() As Boolean
            Get
                Return CType(Me("setLayOutToolBarVisible"),Boolean)
            End Get
            Set
                Me("setLayOutToolBarVisible") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property setDocName() As String
            Get
                Return CType(Me("setDocName"),String)
            End Get
            Set
                Me("setDocName") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property setDocPath() As String
            Get
                Return CType(Me("setDocPath"),String)
            End Get
            Set
                Me("setDocPath") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("True")>  _
        Public Property setWarnLinkedObjectDelete() As Boolean
            Get
                Return CType(Me("setWarnLinkedObjectDelete"),Boolean)
            End Get
            Set
                Me("setWarnLinkedObjectDelete") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Goal")>  _
        Public Property setStruct1sing() As String
            Get
                Return CType(Me("setStruct1sing"),String)
            End Get
            Set
                Me("setStruct1sing") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Purpose")>  _
        Public Property setStruct2sing() As String
            Get
                Return CType(Me("setStruct2sing"),String)
            End Get
            Set
                Me("setStruct2sing") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Output")>  _
        Public Property setStruct3sing() As String
            Get
                Return CType(Me("setStruct3sing"),String)
            End Get
            Set
                Me("setStruct3sing") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Activity")>  _
        Public Property setStruct4sing() As String
            Get
                Return CType(Me("setStruct4sing"),String)
            End Get
            Set
                Me("setStruct4sing") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("50")>  _
        Public Property setDefaultIndicatorType() As Integer
            Get
                Return CType(Me("setDefaultIndicatorType"),Integer)
            End Get
            Set
                Me("setDefaultIndicatorType") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property setShowDetailsLogframe() As Boolean
            Get
                Return CType(Me("setShowDetailsLogframe"),Boolean)
            End Get
            Set
                Me("setShowDetailsLogframe") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("True")>  _
        Public Property setPrintIndicatorsPrintPurposes() As Boolean
            Get
                Return CType(Me("setPrintIndicatorsPrintPurposes"),Boolean)
            End Get
            Set
                Me("setPrintIndicatorsPrintPurposes") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("True")>  _
        Public Property setPrintIndicatorsPrintOutputs() As Boolean
            Get
                Return CType(Me("setPrintIndicatorsPrintOutputs"),Boolean)
            End Get
            Set
                Me("setPrintIndicatorsPrintOutputs") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("True")>  _
        Public Property setPrintIndicatorsPrintOptionValues() As Boolean
            Get
                Return CType(Me("setPrintIndicatorsPrintOptionValues"),Boolean)
            End Get
            Set
                Me("setPrintIndicatorsPrintOptionValues") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("True")>  _
        Public Property setPrintIndicatorsPrintValueRanges() As Boolean
            Get
                Return CType(Me("setPrintIndicatorsPrintValueRanges"),Boolean)
            End Get
            Set
                Me("setPrintIndicatorsPrintValueRanges") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("True")>  _
        Public Property setPrintIndicatorsPrintTargets() As Boolean
            Get
                Return CType(Me("setPrintIndicatorsPrintTargets"),Boolean)
            End Get
            Set
                Me("setPrintIndicatorsPrintTargets") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("True")>  _
        Public Property setPrintIndicatorsPrintActivities() As Boolean
            Get
                Return CType(Me("setPrintIndicatorsPrintActivities"),Boolean)
            End Get
            Set
                Me("setPrintIndicatorsPrintActivities") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("0")>  _
        Public Property setPlanningPeriodView() As Integer
            Get
                Return CType(Me("setPlanningPeriodView"),Integer)
            End Get
            Set
                Me("setPlanningPeriodView") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("0")>  _
        Public Property setPlanningPeriod() As Integer
            Get
                Return CType(Me("setPlanningPeriod"),Integer)
            End Get
            Set
                Me("setPlanningPeriod") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("True")>  _
        Public Property setPrintPlanningShowActivityLinks() As Boolean
            Get
                Return CType(Me("setPrintPlanningShowActivityLinks"),Boolean)
            End Get
            Set
                Me("setPrintPlanningShowActivityLinks") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("0")>  _
        Public Property setPlanningElementsView() As Integer
            Get
                Return CType(Me("setPlanningElementsView"),Integer)
            End Get
            Set
                Me("setPlanningElementsView") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("EUR")>  _
        Public Property setDefaultCurrency() As String
            Get
                Return CType(Me("setDefaultCurrency"),String)
            End Get
            Set
                Me("setDefaultCurrency") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("0")>  _
        Public Property setProjectLogicIndex() As Integer
            Get
                Return CType(Me("setProjectLogicIndex"),Integer)
            End Get
            Set
                Me("setProjectLogicIndex") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Verdana, 11pt")>  _
        Public Property setDefaultFontUI() As Global.System.Drawing.Font
            Get
                Return CType(Me("setDefaultFontUI"),Global.System.Drawing.Font)
            End Get
            Set
                Me("setDefaultFontUI") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Help\Logframer 2 Help.chm")>  _
        Public Property setHelpPath() As String
            Get
                Return CType(Me("setHelpPath"),String)
            End Get
            Set
                Me("setHelpPath") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("en-GB")>  _
        Public Property setLanguage() As String
            Get
                Return CType(Me("setLanguage"),String)
            End Get
            Set
                Me("setLanguage") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Property setRecentFilesList() As Global.System.Collections.Specialized.StringCollection
            Get
                Return CType(Me("setRecentFilesList"),Global.System.Collections.Specialized.StringCollection)
            End Get
            Set
                Me("setRecentFilesList") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("4")>  _
        Public Property setRecentFilesMax() As Integer
            Get
                Return CType(Me("setRecentFilesMax"),Integer)
            End Get
            Set
                Me("setRecentFilesMax") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Verdana, 11pt, style=Bold")>  _
        Public Property setDefaultFontSections() As Global.System.Drawing.Font
            Get
                Return CType(Me("setDefaultFontSections"),Global.System.Drawing.Font)
            End Get
            Set
                Me("setDefaultFontSections") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("White")>  _
        Public Property setDefaultFontSectionColor() As Global.System.Drawing.Color
            Get
                Return CType(Me("setDefaultFontSectionColor"),Global.System.Drawing.Color)
            End Get
            Set
                Me("setDefaultFontSectionColor") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("LightGray")>  _
        Public Property setDefaultColorSectionTop() As Global.System.Drawing.Color
            Get
                Return CType(Me("setDefaultColorSectionTop"),Global.System.Drawing.Color)
            End Get
            Set
                Me("setDefaultColorSectionTop") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Gray")>  _
        Public Property setDefaultColorSectionBottom() As Global.System.Drawing.Color
            Get
                Return CType(Me("setDefaultColorSectionBottom"),Global.System.Drawing.Color)
            End Get
            Set
                Me("setDefaultColorSectionBottom") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Verdana, 10pt")>  _
        Public Property setDefaultFontSortNumbers() As Global.System.Drawing.Font
            Get
                Return CType(Me("setDefaultFontSortNumbers"),Global.System.Drawing.Font)
            End Get
            Set
                Me("setDefaultFontSortNumbers") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("0")>  _
        Public Property setSearchContacts() As Integer
            Get
                Return CType(Me("setSearchContacts"),Integer)
            End Get
            Set
                Me("setSearchContacts") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Property setMyPrinterSettings() As Global.System.Drawing.Printing.PrinterSettings
            Get
                Return CType(Me("setMyPrinterSettings"),Global.System.Drawing.Printing.PrinterSettings)
            End Get
            Set
                Me("setMyPrinterSettings") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("True")>  _
        Public Property setPrintPartnersBorders() As Boolean
            Get
                Return CType(Me("setPrintPartnersBorders"),Boolean)
            End Get
            Set
                Me("setPrintPartnersBorders") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property setPrintPartnersFill() As Boolean
            Get
                Return CType(Me("setPrintPartnersFill"),Boolean)
            End Get
            Set
                Me("setPrintPartnersFill") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property setPrintTargetgroupIdBorders() As Boolean
            Get
                Return CType(Me("setPrintTargetgroupIdBorders"),Boolean)
            End Get
            Set
                Me("setPrintTargetgroupIdBorders") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property setPrintTargetgroupIdFill() As Boolean
            Get
                Return CType(Me("setPrintTargetgroupIdFill"),Boolean)
            End Get
            Set
                Me("setPrintTargetgroupIdFill") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property setPrintPlanningRepeatRowHeaders() As Boolean
            Get
                Return CType(Me("setPrintPlanningRepeatRowHeaders"),Boolean)
            End Get
            Set
                Me("setPrintPlanningRepeatRowHeaders") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("- ")>  _
        Public Property setPrintTargetgroupName() As String
            Get
                Return CType(Me("setPrintTargetgroupName"),String)
            End Get
            Set
                Me("setPrintTargetgroupName") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("0")>  _
        Public Property setPrintTargetgroupSection() As Integer
            Get
                Return CType(Me("setPrintTargetgroupSection"),Integer)
            End Get
            Set
                Me("setPrintTargetgroupSection") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("00000000-0000-0000-0000-000000000000")>  _
        Public Property setPrintIndicatorsTargetgroupGuid() As Global.System.Guid
            Get
                Return CType(Me("setPrintIndicatorsTargetgroupGuid"),Global.System.Guid)
            End Get
            Set
                Me("setPrintIndicatorsTargetgroupGuid") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("0")>  _
        Public Property setPrintIndicatorsSection() As Integer
            Get
                Return CType(Me("setPrintIndicatorsSection"),Integer)
            End Get
            Set
                Me("setPrintIndicatorsSection") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("0")>  _
        Public Property setPrintPmfSection() As Integer
            Get
                Return CType(Me("setPrintPmfSection"),Integer)
            End Get
            Set
                Me("setPrintPmfSection") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("0")>  _
        Public Property setPrintRiskRegisterRiskCategory() As Integer
            Get
                Return CType(Me("setPrintRiskRegisterRiskCategory"),Integer)
            End Get
            Set
                Me("setPrintRiskRegisterRiskCategory") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("0")>  _
        Public Property setPrintPlanningPeriodView() As Integer
            Get
                Return CType(Me("setPrintPlanningPeriodView"),Integer)
            End Get
            Set
                Me("setPrintPlanningPeriodView") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("0")>  _
        Public Property setPrintPlanningElements() As Integer
            Get
                Return CType(Me("setPrintPlanningElements"),Integer)
            End Get
            Set
                Me("setPrintPlanningElements") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Property setPrintPlanningPeriodFrom() As Date
            Get
                Return CType(Me("setPrintPlanningPeriodFrom"),Date)
            End Get
            Set
                Me("setPrintPlanningPeriodFrom") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Property setPrintPlanningPeriodUntil() As Date
            Get
                Return CType(Me("setPrintPlanningPeriodUntil"),Date)
            End Get
            Set
                Me("setPrintPlanningPeriodUntil") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("00000000-0000-0000-0000-000000000000")>  _
        Public Property setPrintPlanningOutputGuid() As Global.System.Guid
            Get
                Return CType(Me("setPrintPlanningOutputGuid"),Global.System.Guid)
            End Get
            Set
                Me("setPrintPlanningOutputGuid") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("0")>  _
        Public Property setPrintPartnersIndex() As Integer
            Get
                Return CType(Me("setPrintPartnersIndex"),Integer)
            End Get
            Set
                Me("setPrintPartnersIndex") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("0")>  _
        Public Property setTimerAutoSave() As Integer
            Get
                Return CType(Me("setTimerAutoSave"),Integer)
            End Get
            Set
                Me("setTimerAutoSave") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property setCloudUserApiKey() As String
            Get
                Return CType(Me("setCloudUserApiKey"),String)
            End Get
            Set
                Me("setCloudUserApiKey") = value
            End Set
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("http://localhost/lfcloud/public/index.php/api/v1/")>  _
        Public ReadOnly Property setServerBaseUri() As String
            Get
                Return CType(Me("setServerBaseUri"),String)
            End Get
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property setCloudUserName() As String
            Get
                Return CType(Me("setCloudUserName"),String)
            End Get
            Set
                Me("setCloudUserName") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property setCloudUserPassword() As String
            Get
                Return CType(Me("setCloudUserPassword"),String)
            End Get
            Set
                Me("setCloudUserPassword") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("7")>  _
        Public Property setIndentIncrement() As String
            Get
                Return CType(Me("setIndentIncrement"),String)
            End Get
            Set
                Me("setIndentIncrement") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("True")>  _
        Public Property setShowDetailsPlanning() As String
            Get
                Return CType(Me("setShowDetailsPlanning"),String)
            End Get
            Set
                Me("setShowDetailsPlanning") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("True")>  _
        Public Property setShowDatesColumns() As Boolean
            Get
                Return CType(Me("setShowDatesColumns"),Boolean)
            End Get
            Set
                Me("setShowDatesColumns") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property setPlanningHideEmptyCells() As Boolean
            Get
                Return CType(Me("setPlanningHideEmptyCells"),Boolean)
            End Get
            Set
                Me("setPlanningHideEmptyCells") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("True")>  _
        Public Property setPlanningActivityLinks() As Boolean
            Get
                Return CType(Me("setPlanningActivityLinks"),Boolean)
            End Get
            Set
                Me("setPlanningActivityLinks") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("True")>  _
        Public Property setPlanningKeyMomentLinks() As String
            Get
                Return CType(Me("setPlanningKeyMomentLinks"),String)
            End Get
            Set
                Me("setPlanningKeyMomentLinks") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property setShowAdvancedIndicatorOptions() As Boolean
            Get
                Return CType(Me("setShowAdvancedIndicatorOptions"),Boolean)
            End Get
            Set
                Me("setShowAdvancedIndicatorOptions") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("True")>  _
        Public Property setShowDurationColumns() As Boolean
            Get
                Return CType(Me("setShowDurationColumns"),Boolean)
            End Get
            Set
                Me("setShowDurationColumns") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property setBudgetHideEmptyCells() As Boolean
            Get
                Return CType(Me("setBudgetHideEmptyCells"),Boolean)
            End Get
            Set
                Me("setBudgetHideEmptyCells") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property setShowLocalCurrencyColumn() As Boolean
            Get
                Return CType(Me("setShowLocalCurrencyColumn"),Boolean)
            End Get
            Set
                Me("setShowLocalCurrencyColumn") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property setShowExchangeRates() As Boolean
            Get
                Return CType(Me("setShowExchangeRates"),Boolean)
            End Get
            Set
                Me("setShowExchangeRates") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property setShowDetailsBudget() As Boolean
            Get
                Return CType(Me("setShowDetailsBudget"),Boolean)
            End Get
            Set
                Me("setShowDetailsBudget") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("True")>  _
        Public Property setPrintPlanningShowDatesColumns() As Boolean
            Get
                Return CType(Me("setPrintPlanningShowDatesColumns"),Boolean)
            End Get
            Set
                Me("setPrintPlanningShowDatesColumns") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("0")>  _
        Public Property setPrintPlanningElementsView() As Integer
            Get
                Return CType(Me("setPrintPlanningElementsView"),Integer)
            End Get
            Set
                Me("setPrintPlanningElementsView") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("True")>  _
        Public Property setPrintPlanningShowKeyMomentLinks() As Boolean
            Get
                Return CType(Me("setPrintPlanningShowKeyMomentLinks"),Boolean)
            End Get
            Set
                Me("setPrintPlanningShowKeyMomentLinks") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("True")>  _
        Public Property setPrintBudgetShowDurationColumns() As Boolean
            Get
                Return CType(Me("setPrintBudgetShowDurationColumns"),Boolean)
            End Get
            Set
                Me("setPrintBudgetShowDurationColumns") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("True")>  _
        Public Property setPrintBudgetShowLocalCurrencyColumns() As Boolean
            Get
                Return CType(Me("setPrintBudgetShowLocalCurrencyColumns"),Boolean)
            End Get
            Set
                Me("setPrintBudgetShowLocalCurrencyColumns") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property setPrintBudgetShowExchangeRates() As Boolean
            Get
                Return CType(Me("setPrintBudgetShowExchangeRates"),Boolean)
            End Get
            Set
                Me("setPrintBudgetShowExchangeRates") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("1")>  _
        Public Property setPrintBudgetPagesWide() As Integer
            Get
                Return CType(Me("setPrintBudgetPagesWide"),Integer)
            End Get
            Set
                Me("setPrintBudgetPagesWide") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("1")>  _
        Public Property setPrintPmfPagesWide() As Integer
            Get
                Return CType(Me("setPrintPmfPagesWide"),Integer)
            End Get
            Set
                Me("setPrintPmfPagesWide") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("0")>  _
        Public Property setPrintIndicatorsMeasurement() As Integer
            Get
                Return CType(Me("setPrintIndicatorsMeasurement"),Integer)
            End Get
            Set
                Me("setPrintIndicatorsMeasurement") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("1")>  _
        Public Property setPrintRiskRegisterPagesWide() As Integer
            Get
                Return CType(Me("setPrintRiskRegisterPagesWide"),Integer)
            End Get
            Set
                Me("setPrintRiskRegisterPagesWide") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("1")>  _
        Public Property setPrintResourcesPagesWide() As Integer
            Get
                Return CType(Me("setPrintResourcesPagesWide"),Integer)
            End Get
            Set
                Me("setPrintResourcesPagesWide") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("2")>  _
        Public Property setPrintAssumptionsSection() As Integer
            Get
                Return CType(Me("setPrintAssumptionsSection"),Integer)
            End Get
            Set
                Me("setPrintAssumptionsSection") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("1")>  _
        Public Property setPrintAssumptionsPagesWide() As Integer
            Get
                Return CType(Me("setPrintAssumptionsPagesWide"),Integer)
            End Get
            Set
                Me("setPrintAssumptionsPagesWide") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("2")>  _
        Public Property setPrintDependenciesSection() As Integer
            Get
                Return CType(Me("setPrintDependenciesSection"),Integer)
            End Get
            Set
                Me("setPrintDependenciesSection") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("1")>  _
        Public Property setPrintDependenciesPagesWide() As Integer
            Get
                Return CType(Me("setPrintDependenciesPagesWide"),Integer)
            End Get
            Set
                Me("setPrintDependenciesPagesWide") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("True")>  _
        Public Property setPrintDependenciesShowDeliverables() As Boolean
            Get
                Return CType(Me("setPrintDependenciesShowDeliverables"),Boolean)
            End Get
            Set
                Me("setPrintDependenciesShowDeliverables") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("True")>  _
        Public Property setPrintPmfShowTargetRowTitles() As Boolean
            Get
                Return CType(Me("setPrintPmfShowTargetRowTitles"),Boolean)
            End Get
            Set
                Me("setPrintPmfShowTargetRowTitles") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("http://www.logframer.eu/")>  _
        Public Property setHelpOnline() As String
            Get
                Return CType(Me("setHelpOnline"),String)
            End Get
            Set
                Me("setHelpOnline") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("http://www.facilidev.eu/")>  _
        Public Property setHelpOnlineFacilidev() As String
            Get
                Return CType(Me("setHelpOnlineFacilidev"),String)
            End Get
            Set
                Me("setHelpOnlineFacilidev") = value
            End Set
        End Property
    End Class
End Namespace

Namespace My
    
    <Global.Microsoft.VisualBasic.HideModuleNameAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()>  _
    Friend Module MySettingsProperty
        
        <Global.System.ComponentModel.Design.HelpKeywordAttribute("My.Settings")>  _
        Friend ReadOnly Property Settings() As Global.FaciliDev.LogFramer.My.MySettings
            Get
                Return Global.FaciliDev.LogFramer.My.MySettings.Default
            End Get
        End Property
    End Module
End Namespace
